env:
  GITHUB_TOKEN: ${{ secrets.APACHE_SYNC_MIDSTREAM_TOKEN }}
jobs:
  sync-main:
    name: Sync main branch
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Create a PR to sync main branch with main-apache
      uses: kiegroup/kie-ci/.ci/actions/main-sync@main
      with:
        main_sync_workflow_exclude_paths: ${{ vars.MAIN_SYNC_WORKFLOW_EXCLUDE_PATHS
          }}
        main_sync_workflow_pr_reviewers: ${{ vars.MAIN_SYNC_WORKFLOW_PR_REVIEWERS
          }}
name: Sync main branch
on:
  repository_dispatch:
    types: trigger-ga___main-sync.yml
