jobs:
  drools-build:
    concurrency:
      cancel-in-progress: true
      group: pr-drools_${{ matrix.os }}_${{ matrix.java-version }}_${{ matrix.maven-version
        }}_${{ github.head_ref }}
    name: ${{ matrix.os }} / Java-${{ matrix.java-version }} / Maven-${{ matrix.maven-version
      }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: ${{ matrix.os == 'ubuntu-latest' }}
      name: Clean Disk Space
      uses: kiegroup/kie-ci/.ci/actions/ubuntu-disk-space@main
    - continue-on-error: true
      if: ${{ matrix.os == 'windows-latest' }}
      name: Support long paths
      uses: kiegroup/kie-ci/.ci/actions/long-paths@main
    - continue-on-error: true
      name: Java and Maven Setup
      uses: kiegroup/kie-ci/.ci/actions/maven@main
      with:
        cache-key-prefix: ${{ runner.os }}-${{ matrix.java-version }}-maven${{ matrix.maven-version
          }}
        java-version: ${{ matrix.java-version }}
        maven-version: ${{ matrix.maven-version }}
    - continue-on-error: true
      env:
        BUILD_MVN_OPTS_CURRENT: -Dfull
      name: Build Chain
      uses: kiegroup/kie-ci/.ci/actions/build-chain@main
      with:
        annotations-prefix: ${{ runner.os }}-${{ matrix.java-version }}/${{ matrix.maven-version
          }}
        definition-file: https://raw.githubusercontent.com/${GROUP:kiegroup}/drools/${BRANCH:main}/.ci/buildchain-config.yaml
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      if: ${{ always() }}
      name: Surefire Report
      uses: kiegroup/kie-ci/.ci/actions/surefire-report@main
      with:
        report_paths: '**/*-reports/TEST-*.xml'
    strategy:
      fail-fast: false
      matrix:
        java-version:
        - 17
        maven-version:
        - 3.9.6
        os:
        - ubuntu-latest
        - windows-latest
    timeout-minutes: 120
name: Drools
on:
  repository_dispatch:
    types: trigger-ga___pr-drools.yml
