jobs:
  drools-ansible:
    concurrency:
      cancel-in-progress: true
      group: pr-drools_ansible_${{ matrix.os }}_${{ matrix.java-version }}_${{ matrix.maven-version
        }}_${{ github.head_ref }}
    name: Ansible Integration / ${{ matrix.os }} / Java-${{ matrix.java-version }}
      / Maven-${{ matrix.maven-version }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: ${{ matrix.os == 'ubuntu-latest' }}
      name: Clean Disk Space
      uses: kiegroup/kie-ci/.ci/actions/ubuntu-disk-space@main
    - continue-on-error: true
      if: ${{ matrix.os == 'windows-latest' }}
      name: Support long paths
      uses: kiegroup/kie-ci/.ci/actions/long-paths@main
    - continue-on-error: true
      name: Java and Maven Setup
      uses: kiegroup/kie-ci/.ci/actions/maven@main
      with:
        allow-snapshots: true
        cache-key-prefix: ${{ runner.os }}-${{ matrix.java-version }}-maven${{ matrix.maven-version
          }}
        java-version: ${{ matrix.java-version }}
        maven-version: ${{ matrix.maven-version }}
    - continue-on-error: true
      name: Build Chain
      uses: kiegroup/kie-ci/.ci/actions/build-chain@main
      with:
        annotations-prefix: ${{ runner.os }}-${{ matrix.java-version }}/${{ matrix.maven-version
          }}
        definition-file: https://raw.githubusercontent.com/${GROUP:kiegroup}/drools-ansible-rulebook-integration/${BRANCH:main}/.ci/pull-request-config.yaml
        github-token: ${{ secrets.GITHUB_TOKEN }}
        starting-project: kiegroup/drools-ansible-rulebook-integration
    strategy:
      fail-fast: false
      matrix:
        java-version:
        - 17
        maven-version:
        - 3.9.6
        os:
        - ubuntu-latest
    timeout-minutes: 120
name: Drools Ansible RuleBook Integration Check
on:
  repository_dispatch:
    types: trigger-ga___pr-drools-ansible.yml
