jobs:
  drools-build:
    concurrency:
      cancel-in-progress: true
      group: pr-drools_docs_${{ matrix.os }}_${{ matrix.java-version }}_${{ matrix.maven-version
        }}_${{ github.head_ref }}
    name: ${{ matrix.os }} / Java-${{ matrix.java-version }} / Maven-${{ matrix.maven-version
      }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Java and Maven Setup
      uses: kiegroup/kie-ci/.ci/actions/maven@main
      with:
        allow-snapshots: true
        cache-key-prefix: ${{ runner.os }}-${{ matrix.java-version }}-maven${{ matrix.maven-version
          }}
        java-version: ${{ matrix.java-version }}
        maven-version: ${{ matrix.maven-version }}
    - continue-on-error: true
      name: Build with Maven
      run: mvn -B clean install --file drools-docs/pom.xml
    strategy:
      fail-fast: false
      matrix:
        java-version:
        - 17
        maven-version:
        - 3.9.6
        os:
        - ubuntu-latest
    timeout-minutes: 120
name: Drools Docs
on:
  repository_dispatch:
    types: trigger-ga___pr-drools-docs.yml
