jobs:
  dsl-tests:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.repository.name }}_dsl_tests-${{ github.head_ref }}
    name: DSL
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: DSL tests
      uses: kiegroup/kie-ci/.ci/actions/dsl-tests@main
      with:
        branch-config-file-repo: kiegroup/drools
        main-config-file-path: .ci/jenkins/config/main.yaml
        main-config-file-repo: kiegroup/drools
        project: drools
name: Jenkins Tests
on:
  repository_dispatch:
    types: trigger-ga___pr-jenkins.yml
