env:
  GITHUB_TOKEN: ${{ secrets.APACHE_SYNC_MIDSTREAM_TOKEN }}
jobs:
  sync-main-apache:
    name: Sync main-apache branch
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Sync main-apache branch with upstream/main
      uses: kiegroup/kie-ci/.ci/actions/upstream-sync@main
      with:
        upstream_remote: https://github.com/apache/incubator-kie-drools.git
name: Sync main-apache branch
on:
  repository_dispatch:
    types: trigger-ga___upstream-sync.yml
